FROM chatbotai-base:latest

WORKDIR /app

# 의존성 파일 및 스크립트 복사
COPY requirements.txt /app/requirements.txt
COPY requirements_llama.txt /app/requirements_llama.txt
COPY src/install_libs.sh /app/install_libs.sh

# 스크립트 실행 권한 부여
RUN chmod +x /app/install_libs.sh

# 볼륨 마운트 포인트
VOLUME ["/opt/python-libs"]

# 기본 명령어
CMD ["/app/install_libs.sh"]